version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements.txt
      - run:
          command: python circleci_test/find_one_template_test.py
          name: Detect test

workflows:
  main:
    jobs:
      - build-and-test